apiVersion: v1
kind: Service
metadata:
  name: ims
spec:
  selector:
    app: ims
  ports:
  - port: 5000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ims
  labels:
    app: ims
spec:
  selector:
    matchLabels:
      app: ims
  replicas: 1
  template:
    metadata:
      labels:
        app: ims
    spec:
      containers:
      - name: ims
        image: icr.io/karthik-docker/karthik-repo@sha256:a190265b8f10906f7501f720b4737c0501d4f539ed496eeab5e3ab76aceaaba0
        ports:
        - containerPort: 5000
        env:
        - name: DISABLE_WEB_APP
          value: "false"